### ISSUE TITLE
Remove flavours for inactive servers

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-android#155]
Apparently `lg-innovation-ke.app` has been[ shut down](https://github.com/medic/medic-projects/issues/7347#issue-595966633), but we are still referencing  to it on [medic-android](https://github.com/medic/medic-android/blob/master/src/livinggoods_innovation_ke/res/values/strings.xml#L4) and building APKs for it atm. Maybe we should remove it or point it to the  [dev instance](https://lg-innovation-ke.dev.medicmobile.org/)  currently used for internal testing. There might be other flavours that are no longer in use.

**Comment by mrsarm** [comment]
OK, going to remove the `livinggoods_innovation_ke` flavor from medic-android, APKs won't be available starting v0.7.3

**Comment by mrsarm** [comment]
Removed at https://github.com/medic/medic-android/pull/150/commits/52c2e915cf15068d16d97f56e93c3b5de539180c

**Comment by mrsarm** [comment]
Close this ticket, the commit mentioned above was part of this other [pull/150](https://github.com/medic/medic-android/pull/150) that was tested and merged under another [issue](https://github.com/medic/medic-android/issues/148), so since v0.7.3 were the changes were pushed to upstream the flavor does not exist any more.
