### ISSUE TITLE
Build separate apks for 32 and 64 bit

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-android#79]
In [this issue](https://github.com/medic/medic/issues/5642) we patched the android app to support 64bit phones. This roughly doubled the size of the apk because both versions of the crosswalk binary are shipped to the phone even though it will only use one.

Investigate methods of publishing two different apks, one for 32bit and one for 64bit so we support all phones but clients only have to download the version they'll use.

Documentation:

- https://developer.android.com/google/play/publishing/multiple-apks
- https://developer.android.com/studio/build/configure-apk-splits

**Comment by kennsippell** [comment]
FYI - I've addressed this in my work in 3.6 as part of the travis build.  Should have a code review out tomorrow.

**Comment by kennsippell** [comment]
Note for AT - I've merged the build because I can't fully test this process until it is on master. Build output can be seen at https://github.com/medic/medic-android/releases/tag/v0.4.25. This build output is also being acceptance tested by @kitsao and the MoH Zanzibar team.

**Comment by ngaruko** [comment]
@kennsippell I am trying to test this by `Creating a git tag starting with v, e.g. v1.2.3 and pushing the tag to GitHub` as in the [documentation](https://github.com/medic/medic-android#publishing). Unfortunately the build is failing on[ travis](https://travis-ci.org/medic/medic-android/jobs/554089235)..
![image](https://user-images.githubusercontent.com/6979995/60645637-51b67480-9e8d-11e9-817d-b461e277c0eb.png)

But the expectation here, is if the travis job was successful, I would see a bunch of apks [released](https://github.com/medic/medic-android/releases)?

**Comment by kennsippell** [comment]
@ngaruko The tag must be for a commit in the `master` branch. It must also be larger than the current release number in order to deploy to the app store. Given that it must be larger, we probably shouldn't confuse the latest release train with this. I created the v0.4.30 just 2 days ago and tested this e2e [here](https://github.com/medic/medic-android/releases/tag/v0.4.30) and on Play Store :).  

But I'd be curious to know how the APKs on GitHub behave when side loading. If you side load v0.4.29 and then side load v0.4.30, does it upgrade smoothly? or does it force an uninstall?

**Comment by ngaruko** [comment]
Thanks @kennsippell 
Side loading also works fine. Version updated automatically once the new apk is installed. Will close this.

**Comment by kennsippell** [comment]
Sadly not much I can do about that "App not Installed" error. That is just part of the complexity of side-loading. Thanks for the AT!
